# Generated by Django 3.0 on 2019-12-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distance', models.FloatField(help_text='Yards need to get the next first down')),
                ('Down', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], max_length=100)),
                ('Your_Team', models.CharField(blank=True, choices=[('NE', 'NE'), ('KC', 'KC'), ('BUF', 'BUF'), ('NYJ', 'NYJ'), ('ATL', 'ATL'), ('CHI', 'CHI'), ('CIN', 'CIN'), ('BAL', 'BAL'), ('CLE', 'CLE'), ('PIT', 'PIT'), ('ARI', 'ARI'), ('DET', 'DET'), ('JAX', 'JAX'), ('HOU', 'HOU'), ('OAK', 'OAK'), ('TEN', 'TEN'), ('WAS', 'WAS'), ('PHI', 'PHI'), ('LA', 'LA'), ('IND', 'IND'), ('SEA', 'SEA'), ('GB', 'GB'), ('CAR', 'CAR'), ('SF', 'SF'), ('DAL', 'DAL'), ('NYG', 'NYG'), ('NO', 'NO'), ('MIN', 'MIN'), ('DEN', 'DEN'), ('LAC', 'LAC'), ('TB', 'TB'), ('MIA', 'MIA')], max_length=100)),
                ('Offense', models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=100)),
                ('Opponent', models.CharField(blank=True, choices=[('NE', 'NE'), ('KC', 'KC'), ('BUF', 'BUF'), ('NYJ', 'NYJ'), ('ATL', 'ATL'), ('CHI', 'CHI'), ('CIN', 'CIN'), ('BAL', 'BAL'), ('CLE', 'CLE'), ('PIT', 'PIT'), ('ARI', 'ARI'), ('DET', 'DET'), ('JAX', 'JAX'), ('HOU', 'HOU'), ('OAK', 'OAK'), ('TEN', 'TEN'), ('WAS', 'WAS'), ('PHI', 'PHI'), ('LA', 'LA'), ('IND', 'IND'), ('SEA', 'SEA'), ('GB', 'GB'), ('CAR', 'CAR'), ('SF', 'SF'), ('DAL', 'DAL'), ('NYG', 'NYG'), ('NO', 'NO'), ('MIN', 'MIN'), ('DEN', 'DEN'), ('LAC', 'LAC'), ('TB', 'TB'), ('MIA', 'MIA')], max_length=100)),
            ],
        ),
    ]
